services:
  database:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: 'db'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'root'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@pgadmin.org'
      PGADMIN_DEFAULT_PASSWORD: 'root'
    ports:
      - '8080:80'
    networks:
      - pg-network

networks:
  pg-network:
    driver: bridge

volumes:
  postgres-data: